### ISSUE TITLE
Add a search option to the cli

### ISSUE THREAD

**Issue by ibLeDy** [ibLeDy/timezone-converter#25]
This would add a `--search` option to the cli, which can be used to search timezones by name.

Examples: 

```bash
$ timezone-converter --search "new york"
Found 1 timezone: "new_york"
```

```bash
$ timezone-converter --search mad
Found 2 timezones: "madeira", "madrid"
```

**Comment by 26tanishabanik** [comment]
@ibLeDy  I would like to work on this issue, kindly assign this issue to me.

**Comment by ibLeDy** [comment]
@26tanishabanik So sorry, this issue is already being worked on, but seems like I forgot to assign it, my bad.

With that said, you're free to take any other issue that is unassigned.

**Comment by drzcola** [comment]
@ibLeDy we have the "--search" as argument. But "-s" is already used for single, so we can either keep it just as "--search" or use another one for the short version of the argument.

**Comment by ibLeDy** [comment]
I think we can just use `--search` and `-S` as a short version
