### ISSUE TITLE
Output close matches when the timezone argument is not correct

### ISSUE THREAD

**Issue by ibLeDy** [ibLeDy/timezone-converter#4]
When the user inputs a timezone that is not in the list, we should fuzzy search for similar ones to offer a suggestion.

We can also have a fuzzy search capability in case the `--list` option is not useful enough

**Comment by ibLeDy** [comment]
Seems like this can be done in an easy manner, even without external dependencies, as per https://twitter.com/pybites/status/1396102910627487749

Seems like `django` is using it for `manage.py` too, so we can learn from their implementation: https://github.com/django/django/pull/9703/files

**Comment by drzcola** [comment]
Hello @ibLeDy,

I'd like to give a hand with this.

**Comment by ibLeDy** [comment]
Sure, I'll assign the issue to you
