### ISSUE TITLE
Add automated Docker image build and push to the `deployment` workflow

### ISSUE THREAD

**Issue by ibLeDy** [ibLeDy/timezone-converter#43]
- The image should be pushed to this repo: https://hub.docker.com/r/bledy/timezone-converter (I guess we would need a `secret`, for example `DOCKER_HUB_TOKEN`).
- The image should use the same tag as the release that triggered the workflow (without the `v` prefix)

**Comment by FaithKovi** [comment]
Hello, @ibLeDy I would like to work on this issue. Is there any specification you would want in implementing this?

**Comment by FaithKovi** [comment]
@ibLeDy  For the second one, do yo mean the tag should be the github commit SHA that triggered the workflow?

**Comment by ibLeDy** [comment]
@FaithKovi 

This automation should be added to the `deployment` workflow, which is triggered once a new release is created on Github:

https://github.com/ibLeDy/timezone-converter/blob/ee8c8b8e2a47c1576b52c113eb2319d4169bcd50/.github/workflows/deployment.yml#L3-L6

As you can see below, I use [SemVer](https://semver.org/), all of the releases have the version in the title, and the commit gets tagged, so I guess the easiest and most consistent would be to use the commit tag (and then removing the `v` prefix).

https://github.com/ibLeDy/timezone-converter/releases

**Comment by FaithKovi** [comment]
@ibLeDy 
I have created a pull request for this issue. Please review and let me know if there are changes to be made.
There are two secrets to be added: DOCKERHUB_USERNAME and DOCKERHUB_TOKEN
The workflow builds the docker image and pushes it to docker hub

**Comment by ibLeDy** [comment]
I had to do [a small fix](https://github.com/ibLeDy/timezone-converter/commit/598d7e68d764d16d579e3111193b5d3cb40f8601), but works as intended, thanks for your contribution!
